import { Attributes, HuntingGround, Monster, Skills, Vocation } from './types';

export interface VocationDefinition {
  id: Vocation;
  name: string;
  description: string;
  primarySkill: keyof Skills;
  hpPerLevel: number;
  mpPerLevel: number;
  baseHp: number;
  baseMp: number;
  startingAttributes: Attributes;
  spriteColor: string;
  weaponBase: number;
}

export const VOCATION_DEFINITIONS: Record<Vocation, VocationDefinition> = {
  KNIGHT: {
    id: 'KNIGHT',
    name: 'Cavaleiro',
    description: 'Guerreiro corpo a corpo de alta resistência. Combate na linha de frente com espada e escudo.',
    primarySkill: 'MELEE',
    hpPerLevel: 15,
    mpPerLevel: 2,
    baseHp: 150,
    baseMp: 30,
    startingAttributes: { STR: 8, DEX: 4, INT: 2, VIT: 6 },
    spriteColor: '#c0392b',
    weaponBase: 8,
  },
  PALADIN: {
    id: 'PALADIN',
    name: 'Paladino',
    description: 'Combatente à distância, ágil e versátil. Ataca com arco enquanto mantém boa defesa.',
    primarySkill: 'DISTANCE',
    hpPerLevel: 11,
    mpPerLevel: 4,
    baseHp: 120,
    baseMp: 60,
    startingAttributes: { STR: 5, DEX: 8, INT: 4, VIT: 3 },
    spriteColor: '#27ae60',
    weaponBase: 7,
  },
  SORCERER: {
    id: 'SORCERER',
    name: 'Sorcerer',
    description: 'Mago ofensivo com magias devastadoras, porém frágil. Depende de inteligência e mana.',
    primarySkill: 'MAGIC',
    hpPerLevel: 7,
    mpPerLevel: 9,
    baseHp: 85,
    baseMp: 110,
    startingAttributes: { STR: 2, DEX: 3, INT: 10, VIT: 5 },
    spriteColor: '#8e44ad',
    weaponBase: 9,
  },
  DRUID: {
    id: 'DRUID',
    name: 'Druida',
    description: 'Mago da natureza, equilibra dano mágico e resistência. Versátil em qualquer terreno.',
    primarySkill: 'MAGIC',
    hpPerLevel: 9,
    mpPerLevel: 8,
    baseHp: 95,
    baseMp: 100,
    startingAttributes: { STR: 3, DEX: 4, INT: 9, VIT: 4 },
    spriteColor: '#16a085',
    weaponBase: 8,
  },
};

export const MONSTERS: Record<string, Monster> = {
  rat: {
    id: 'rat',
    name: 'Rato Selvagem',
    hp: 20,
    attack: 4,
    defense: 1,
    xpReward: 6,
    goldMin: 1,
    goldMax: 4,
    trophyName: 'Cauda de Rato',
    trophyChance: 0.15,
    color: '#7f8c8d',
    shape: 'blob',
  },
  rotworm: {
    id: 'rotworm',
    name: 'Verme Podre',
    hp: 35,
    attack: 7,
    defense: 2,
    xpReward: 12,
    goldMin: 2,
    goldMax: 6,
    trophyName: 'Casulo Podre',
    trophyChance: 0.12,
    color: '#6b8e23',
    shape: 'blob',
  },
  cave_spider: {
    id: 'cave_spider',
    name: 'Aranha de Caverna',
    hp: 55,
    attack: 11,
    defense: 3,
    xpReward: 20,
    goldMin: 3,
    goldMax: 9,
    trophyName: 'Presa de Aranha',
    trophyChance: 0.1,
    color: '#2c3e50',
    shape: 'spider',
  },
  skeleton: {
    id: 'skeleton',
    name: 'Esqueleto Guerreiro',
    hp: 110,
    attack: 18,
    defense: 6,
    xpReward: 42,
    goldMin: 8,
    goldMax: 20,
    trophyName: 'Osso Antigo',
    trophyChance: 0.1,
    color: '#ecf0f1',
    shape: 'skeleton',
  },
  ghoul: {
    id: 'ghoul',
    name: 'Carniçal',
    hp: 150,
    attack: 24,
    defense: 8,
    xpReward: 60,
    goldMin: 12,
    goldMax: 28,
    trophyName: 'Garra Podre',
    trophyChance: 0.08,
    color: '#5d6d7e',
    shape: 'blob',
  },
  bandit: {
    id: 'bandit',
    name: 'Bandido das Ruínas',
    hp: 130,
    attack: 22,
    defense: 9,
    xpReward: 55,
    goldMin: 15,
    goldMax: 40,
    trophyName: 'Bolsa de Moedas',
    trophyChance: 0.1,
    color: '#a04000',
    shape: 'skeleton',
  },
  frost_wolf: {
    id: 'frost_wolf',
    name: 'Lobo Gélido',
    hp: 260,
    attack: 34,
    defense: 12,
    xpReward: 110,
    goldMin: 20,
    goldMax: 50,
    trophyName: 'Pelo Congelado',
    trophyChance: 0.09,
    color: '#aed6f1',
    shape: 'wolf',
  },
  ice_golem: {
    id: 'ice_golem',
    name: 'Golem de Gelo',
    hp: 400,
    attack: 45,
    defense: 20,
    xpReward: 180,
    goldMin: 30,
    goldMax: 70,
    trophyName: 'Núcleo Congelado',
    trophyChance: 0.07,
    color: '#5dade2',
    shape: 'blob',
  },
  frost_troll: {
    id: 'frost_troll',
    name: 'Troll da Geada',
    hp: 340,
    attack: 40,
    defense: 15,
    xpReward: 150,
    goldMin: 25,
    goldMax: 60,
    trophyName: 'Dente de Troll',
    trophyChance: 0.08,
    color: '#85c1e9',
    shape: 'blob',
  },
  wyrmling: {
    id: 'wyrmling',
    name: 'Wyrmling',
    hp: 600,
    attack: 60,
    defense: 25,
    xpReward: 320,
    goldMin: 50,
    goldMax: 120,
    trophyName: 'Escama Jovem',
    trophyChance: 0.06,
    color: '#e67e22',
    shape: 'dragon',
  },
  drake: {
    id: 'drake',
    name: 'Drake',
    hp: 850,
    attack: 78,
    defense: 32,
    xpReward: 480,
    goldMin: 80,
    goldMax: 180,
    trophyName: 'Garra de Drake',
    trophyChance: 0.05,
    color: '#d35400',
    shape: 'dragon',
  },
  elder_dragon: {
    id: 'elder_dragon',
    name: 'Dragão Ancião',
    hp: 1500,
    attack: 110,
    defense: 45,
    xpReward: 900,
    goldMin: 150,
    goldMax: 350,
    trophyName: 'Escama Ancestral',
    trophyChance: 0.04,
    color: '#922b21',
    shape: 'dragon',
  },
};

export const HUNTING_GROUNDS: HuntingGround[] = [
  {
    id: 'rookie_fields',
    name: 'Campos Iniciantes',
    description: 'Planícies tranquilas infestadas de ratos e vermes. Ideal para os primeiros níveis.',
    minLevel: 1,
    monsterIds: ['rat', 'rotworm', 'cave_spider'],
    backgroundGradient: 'linear-gradient(180deg, #8fbf6f 0%, #5a8f4a 100%)',
  },
  {
    id: 'ancient_ruins',
    name: 'Ruínas Antigas',
    description: 'Ruínas esquecidas guardadas por mortos-vivos e bandidos.',
    minLevel: 15,
    monsterIds: ['skeleton', 'ghoul', 'bandit'],
    backgroundGradient: 'linear-gradient(180deg, #8d7b68 0%, #4e4237 100%)',
  },
  {
    id: 'frozen_caverns',
    name: 'Cavernas Geladas',
    description: 'Um labirinto gelado habitado por criaturas resistentes ao frio.',
    minLevel: 35,
    monsterIds: ['frost_wolf', 'frost_troll', 'ice_golem'],
    backgroundGradient: 'linear-gradient(180deg, #d6eaf8 0%, #85c1e9 100%)',
  },
  {
    id: 'dragons_lair',
    name: 'Covil dos Dragões',
    description: 'A toca lendária dos dragões. Somente os caçadores mais fortes sobrevivem.',
    minLevel: 60,
    monsterIds: ['wyrmling', 'drake', 'elder_dragon'],
    backgroundGradient: 'linear-gradient(180deg, #7b241c 0%, #1c1c1c 100%)',
  },
];

export const ATTRIBUTE_POINTS_PER_LEVEL = 3;
